/**
 * Booking Status
 */
export enum BookingStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED_BY_PARENT = 'CANCELLED_BY_PARENT',
  CANCELLED_BY_TUTOR = 'CANCELLED_BY_TUTOR',
  CANCELLED_BY_ADMIN = 'CANCELLED_BY_ADMIN',
  NO_SHOW_PARENT = 'NO_SHOW_PARENT',
  NO_SHOW_TUTOR = 'NO_SHOW_TUTOR',
  RESCHEDULED = 'RESCHEDULED',
}

/**
 * Session Type
 */
export enum SessionType {
  TRIAL = 'TRIAL',
  REGULAR = 'REGULAR',
  MAKEUP = 'MAKEUP',
  ASSESSMENT = 'ASSESSMENT',
}

